pipeline {
    agent any

    environment {
        APP_NAME = "web-app-container"
        DOCKER_IMAGE = "olga/web-app:latest"
    }

    stages {
        stage('Build') {
            steps {
                // Сборка образа (задание 4)
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Test') {
            steps {
                // Запуск тестов внутри контейнера (задание 5)
                sh "docker run --rm ${DOCKER_IMAGE} npm test"
            }
        }

        stage('Deploy') {
            steps {
                // Очистка старых контейнеров (задание 11)
                sh "docker stop ${APP_NAME} || true"
                sh "docker rm ${APP_NAME} || true"
                // Запуск нового контейнера (задание 8)
                sh "docker run -d -p 80:8080 --name ${APP_NAME} ${DOCKER_IMAGE}"
            }
        }
    }

    post {
        // Уведомление о статусе (задание 7)
        failure {
            echo "Pipeline failed! Sending alert..."
        }
        success {
            echo "Pipeline finished successfully."
        }
    }
}